version: '3.8'

services:
  backend:
    build:
      context: ../../  # 上下文设置为项目根目录
      dockerfile: docker/backend/Dockerfile
    container_name: salary_system_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:810705@host.docker.internal:5432/salary_system_v2
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 如果数据库在宿主机运行，则不需要此depends_on
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      - salary_network

networks:
  salary_network:
    driver: bridge 