-- 备份时间: 2025-06-09 08:33:35.352156
-- 原始视图定义备份

CREATE OR REPLACE VIEW reports.v_comprehensive_employee_payroll AS
 WITH personnel_hierarchy AS (
         WITH RECURSIVE category_tree AS (
                 SELECT personnel_categories.id,
                    personnel_categories.name,
                    personnel_categories.parent_category_id,
                    personnel_categories.id AS root_id,
                    personnel_categories.name AS root_name,
                    0 AS level
                   FROM hr.personnel_categories
                  WHERE personnel_categories.parent_category_id IS NULL
                UNION ALL
                 SELECT pc_1.id,
                    pc_1.name,
                    pc_1.parent_category_id,
                    ct.root_id,
                    ct.root_name,
                    ct.level + 1
                   FROM hr.personnel_categories pc_1
                     JOIN category_tree ct ON pc_1.parent_category_id = ct.id
                )
         SELECT category_tree.id AS category_id,
            category_tree.root_id,
            category_tree.root_name
           FROM category_tree
        )
 SELECT pe.id AS "薪资条目id",
    pe.employee_id AS "员工id",
    pe.payroll_period_id AS "薪资期间id",
    pe.payroll_run_id AS "薪资运行id",
    e.employee_code AS "员工编号",
    e.first_name AS "名",
    e.last_name AS "姓",
    COALESCE(e.last_name::text || e.first_name::text, e.first_name::text, e.last_name::text, '未知姓名'::text) AS "姓名",
    e.id_number AS "身份证号",
    e.phone_number AS "电话",
    e.email AS "邮箱",
    e.hire_date AS "入职日期",
    COALESCE(e.is_active, false) AS "员工状态",
    COALESCE(d.name, '未分配部门'::character varying) AS "部门名称",
    COALESCE(pos.name, '未分配职位'::character varying) AS "职位名称",
    COALESCE(pc.name, '未分类'::character varying) AS "人员类别",
    COALESCE(ph.root_name, '未分类'::character varying) AS "根人员类别",
    COALESCE(pp.name, '未知期间'::character varying) AS "薪资期间名称",
    pp.start_date AS "薪资期间开始日期",
    pp.end_date AS "薪资期间结束日期",
    pp.pay_date AS "薪资发放日期",
    pr.run_date AS "薪资运行日期",
    COALESCE(pe.gross_pay, 0.00) AS "应发合计",
    COALESCE(pe.total_deductions, 0.00) AS "扣除合计",
    COALESCE(pe.net_pay, 0.00) AS "实发合计",
    COALESCE(((pe.earnings_details -> 'MONTHLY_PERFORMANCE_BONUS'::text) ->> 'amount'::text)::numeric, 0.00) AS "月奖励绩效",
    COALESCE(((pe.earnings_details -> 'BASIC_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "基本工资",
    COALESCE(((pe.earnings_details -> 'ONLY_CHILD_PARENT_BONUS'::text) ->> 'amount'::text)::numeric, 0.00) AS "独生子女父母奖励金",
    COALESCE(((pe.earnings_details -> 'POSITION_TECH_GRADE_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "职务技术等级工资",
    COALESCE(((pe.earnings_details -> 'TRAFFIC_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "公务交通补贴",
    COALESCE(((pe.earnings_details -> 'GRADE_POSITION_LEVEL_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "级别岗位级别工资",
    COALESCE(((pe.earnings_details -> 'PERFORMANCE_BONUS'::text) ->> 'amount'::text)::numeric, 0.00) AS "奖励性绩效工资",
    COALESCE(((pe.earnings_details -> 'BASIC_PERFORMANCE_AWARD'::text) ->> 'amount'::text)::numeric, 0.00) AS "基础绩效奖",
    COALESCE(((pe.earnings_details -> 'POSITION_SALARY_GENERAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "岗位工资",
    COALESCE(((pe.earnings_details -> 'BASIC_PERFORMANCE_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "基础性绩效工资",
    COALESCE(((pe.earnings_details -> 'BACK_PAY'::text) ->> 'amount'::text)::numeric, 0.00) AS "补发工资",
    COALESCE(((pe.earnings_details -> 'GRADE_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "级别工资",
    COALESCE(((pe.earnings_details -> 'PERFORMANCE_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "绩效工资",
    COALESCE(((pe.earnings_details -> 'POSITION_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "岗位职务补贴",
    COALESCE(((pe.earnings_details -> 'ALLOWANCE_GENERAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "补助",
    COALESCE(((pe.earnings_details -> 'SALARY_GRADE'::text) ->> 'amount'::text)::numeric, 0.00) AS "薪级工资",
    COALESCE(((pe.earnings_details -> 'BASIC_PERFORMANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "月基础绩效",
    COALESCE(((pe.earnings_details -> 'GENERAL_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "津贴",
    COALESCE(((pe.earnings_details -> 'PETITION_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "信访工作人员岗位工作津贴",
    COALESCE(((pe.earnings_details -> 'QUARTERLY_PERFORMANCE_ASSESSMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "季度绩效考核薪酬",
    COALESCE(((pe.earnings_details -> 'PERFORMANCE_BONUS_BACK_PAY'::text) ->> 'amount'::text)::numeric, 0.00) AS "奖励绩效补发",
    COALESCE(((pe.earnings_details -> 'REFORM_ALLOWANCE_1993'::text) ->> 'amount'::text)::numeric, 0.00) AS "九三年工改保留津补贴",
    COALESCE(((pe.earnings_details -> 'CIVIL_STANDARD_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "公务员规范后津补贴",
    COALESCE(((pe.earnings_details -> 'PROBATION_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "试用期工资",
    COALESCE(((pe.earnings_details -> 'STAFF_SALARY_GRADE'::text) ->> 'amount'::text)::numeric, 0.00) AS "事业单位人员薪级工资",
    COALESCE(((pe.earnings_details -> 'TOWNSHIP_ALLOWANCE'::text) ->> 'amount'::text)::numeric, 0.00) AS "乡镇工作补贴",
    COALESCE(((pe.earnings_details -> 'QUARTERLY_PERFORMANCE_Q1'::text) ->> 'amount'::text)::numeric, 0.00) AS "一季度绩效考核薪酬",
    COALESCE(((pe.deductions_details -> 'MEDICAL_INS_PERSONAL_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险个人缴纳金额",
    COALESCE(((pe.deductions_details -> 'MEDICAL_INS_PERSONAL_TOTAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险个人应缴总额",
    COALESCE(((pe.deductions_details -> 'OCCUPATIONAL_PENSION_PERSONAL_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金个人应缴费额",
    COALESCE(((pe.deductions_details -> 'PENSION_PERSONAL_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "养老保险个人应缴金额",
    COALESCE(((pe.deductions_details -> 'PERSONAL_INCOME_TAX'::text) ->> 'amount'::text)::numeric, 0.00) AS "个人所得税",
    COALESCE(((pe.deductions_details -> 'UNEMPLOYMENT_PERSONAL_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "失业保险个人应缴金额",
    COALESCE(((pe.deductions_details -> 'ONE_TIME_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "一次性补扣发",
    COALESCE(((pe.deductions_details -> 'PERFORMANCE_BONUS_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "绩效奖金补扣发",
    COALESCE(((pe.deductions_details -> 'REWARD_PERFORMANCE_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "奖励绩效补扣发",
    COALESCE(((pe.deductions_details -> 'HOUSING_FUND_PERSONAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "个人缴住房公积金",
    COALESCE(((pe.deductions_details -> 'PERFORMANCE_BONUS_DEDUCTION_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "绩效奖金补扣发2",
    COALESCE(((pe.deductions_details -> 'SOCIAL_INSURANCE_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "补扣社保",
    COALESCE(((pe.deductions_details -> 'REFUND_DEDUCTION_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "补扣退款",
    COALESCE(((pe.deductions_details -> 'MEDICAL_2022_DEDUCTION_ADJUSTMENT'::text) ->> 'amount'::text)::numeric, 0.00) AS "补扣2022年医保款",
    COALESCE(((pe.deductions_details -> 'INJURY_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "工伤单位应缴金额",
    COALESCE(((pe.deductions_details -> 'MEDICAL_INS_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险单位缴纳金额",
    COALESCE(((pe.deductions_details -> 'MEDICAL_INS_EMPLOYER_TOTAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险单位应缴总额",
    COALESCE(((pe.deductions_details -> 'OCCUPATIONAL_PENSION_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金单位应缴费额",
    COALESCE(((pe.deductions_details -> 'PENSION_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "养老保险单位应缴金额",
    COALESCE(((pe.deductions_details -> 'SERIOUS_ILLNESS_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "大病医疗单位缴纳",
    COALESCE(((pe.deductions_details -> 'UNEMPLOYMENT_EMPLOYER_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "失业保险单位应缴金额",
    COALESCE(((pe.deductions_details -> 'HOUSING_FUND_EMPLOYER'::text) ->> 'amount'::text)::numeric, 0.00) AS "单位缴住房公积金",
    COALESCE(((pe.calculation_inputs -> 'MEDICAL_INS_BASE'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险缴费基数",
    COALESCE(((pe.calculation_inputs -> 'MEDICAL_INS_BASE_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险缴费工资",
    COALESCE(((pe.calculation_inputs -> 'MEDICAL_INS_PAY_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险缴费工资2",
    COALESCE(((pe.calculation_inputs -> 'OCCUPATIONAL_PENSION_BASE'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金缴费基数",
    COALESCE(((pe.calculation_inputs -> 'OCCUPATIONAL_PENSION_PAY_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金缴费工资",
    COALESCE(((pe.calculation_inputs -> 'PENSION_BASE'::text) ->> 'amount'::text)::numeric, 0.00) AS "养老缴费基数",
    COALESCE(((pe.calculation_inputs -> 'TAX_BASE'::text) ->> 'amount'::text)::numeric, 0.00) AS "计税基数",
    COALESCE(((pe.calculation_inputs -> 'HOUSING_FUND_BASE'::text) ->> 'amount'::text)::numeric, 0.00) AS "住房公积金缴费基数",
    COALESCE(((pe.calculation_inputs -> 'MEDICAL_INS_EMPLOYER_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险单位缴纳费率",
    COALESCE(((pe.calculation_inputs -> 'MEDICAL_INS_PERSONAL_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "医疗保险个人缴纳费率",
    COALESCE(((pe.calculation_inputs -> 'OCCUPATIONAL_PENSION_EMPLOYER_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金单位缴费费率",
    COALESCE(((pe.calculation_inputs -> 'OCCUPATIONAL_PENSION_PERSONAL_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "职业年金个人费率",
    COALESCE(((pe.calculation_inputs -> 'PENSION_EMPLOYER_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "养老单位缴费比例",
    COALESCE(((pe.calculation_inputs -> 'PENSION_PERSONAL_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "养老个人缴费比例",
    COALESCE(((pe.calculation_inputs -> 'SERIOUS_ILLNESS_EMPLOYER_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "大病医疗单位缴纳费率",
    COALESCE(((pe.calculation_inputs -> 'TAX_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "适用税率",
    COALESCE(((pe.calculation_inputs -> 'HOUSING_FUND_PERSONAL_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "住房公积金个人缴费比例",
    COALESCE(((pe.calculation_inputs -> 'HOUSING_FUND_EMPLOYER_RATE'::text) ->> 'amount'::text)::numeric, 0.00) AS "住房公积金单位缴费比例",
    COALESCE(((pe.calculation_inputs -> 'AFTER_TAX_SALARY'::text) ->> 'amount'::text)::numeric, 0.00) AS "税后工资",
    COALESCE(((pe.calculation_inputs -> 'QUICK_DEDUCTION'::text) ->> 'amount'::text)::numeric, 0.00) AS "速算扣除数",
    COALESCE(((pe.calculation_inputs -> 'TAXABLE_INCOME'::text) ->> 'amount'::text)::numeric, 0.00) AS "应纳税所得额",
    COALESCE(((pe.calculation_inputs -> 'TAX_DEDUCTION_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "扣除额",
    COALESCE(((pe.calculation_inputs -> 'TAX_EXEMPT_AMOUNT'::text) ->> 'amount'::text)::numeric, 0.00) AS "免税额",
    COALESCE(((pe.calculation_inputs -> 'UNIFIED_PAYROLL_FLAG'::text) ->> 'amount'::text)::boolean, true) AS "工资统发",
    COALESCE(((pe.calculation_inputs -> 'FISCAL_SUPPORT_FLAG'::text) ->> 'amount'::text)::boolean, true) AS "财政供养",
    COALESCE(((pe.calculation_inputs -> 'ANNUAL_FIXED_SALARY_TOTAL'::text) ->> 'amount'::text)::numeric, 0.00) AS "固定薪酬全年应发数",
    COALESCE(pe.status_lookup_value_id, 1::bigint) AS "状态id",
    COALESCE(pe.remarks, ''::text) AS "备注",
    pe.audit_status AS "审计状态",
    pe.audit_timestamp AS "审计时间",
    pe.auditor_id AS "审计员id",
    pe.audit_notes AS "审计备注",
    pe.version AS "版本号",
    COALESCE(pe.calculated_at, pe.updated_at, now()) AS "计算时间",
    pe.updated_at AS "更新时间",
    pe.earnings_details AS "原始应发明细",
    pe.deductions_details AS "原始扣除明细",
    pe.calculation_inputs AS "原始计算输入",
    pe.calculation_log AS "原始计算日志"
   FROM payroll.payroll_entries pe
     LEFT JOIN hr.employees e ON pe.employee_id = e.id
     LEFT JOIN hr.departments d ON e.department_id = d.id
     LEFT JOIN hr.positions pos ON e.actual_position_id = pos.id
     LEFT JOIN hr.personnel_categories pc ON e.personnel_category_id = pc.id
     LEFT JOIN personnel_hierarchy ph ON pc.id = ph.category_id
     LEFT JOIN payroll.payroll_periods pp ON pe.payroll_period_id = pp.id
     LEFT JOIN payroll.payroll_runs pr ON pe.payroll_run_id = pr.id;
