"""add_employment_start_date_to_raw_salary_staging

Revision ID: 1a1e8747b7cc
Revises: 6dd91c177096
Create Date: 2025-05-07 06:21:00.000965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1e8747b7cc'
down_revision: Union[str, None] = '6dd91c177096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_salary_data_staging', sa.Column('employment_start_date', sa.Date(), nullable=True), schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_salary_data_staging', 'employment_start_date', schema='staging')
    # ### end Alembic commands ###
