"""remove_sal_employee_unique_id_from_consolidated_model

Revision ID: 46c5464fae9b
Revises: b59efb0afd10
Create Date: 2025-05-07 05:59:19.176637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c5464fae9b'
down_revision: Union[str, None] = 'b59efb0afd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
