"""adjust_sal_ref_step_type_and_add_missing_sal_cols

Revision ID: 6dd91c177096
Revises: 2c1358ced27a
Create Date: 2025-05-07 06:16:27.376644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd91c177096'
down_revision: Union[str, None] = '2c1358ced27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consolidated_data', 'sal_ref_official_salary_step',
                    existing_type=sa.VARCHAR(), 
                    type_=sa.Text(),
                    nullable=True, 
                    schema='staging')

    op.add_column('consolidated_data', sa.Column('sal_position_rank', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_gender', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_ethnicity', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_date_of_birth', sa.Date(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_education_level', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_service_interruption_years', sa.Numeric(precision=15, scale=2), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_continuous_service_years', sa.Numeric(precision=15, scale=2), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_actual_position', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_actual_position_start_date', sa.Date(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_position_level_start_date', sa.Date(), nullable=True), schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consolidated_data', 'sal_position_level_start_date', schema='staging')
    op.drop_column('consolidated_data', 'sal_actual_position_start_date', schema='staging')
    op.drop_column('consolidated_data', 'sal_actual_position', schema='staging')
    op.drop_column('consolidated_data', 'sal_continuous_service_years', schema='staging')
    op.drop_column('consolidated_data', 'sal_service_interruption_years', schema='staging')
    op.drop_column('consolidated_data', 'sal_education_level', schema='staging')
    op.drop_column('consolidated_data', 'sal_date_of_birth', schema='staging')
    op.drop_column('consolidated_data', 'sal_ethnicity', schema='staging')
    op.drop_column('consolidated_data', 'sal_gender', schema='staging')
    op.drop_column('consolidated_data', 'sal_position_rank', schema='staging')

    op.alter_column('consolidated_data', 'sal_ref_official_salary_step',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(), 
                    nullable=True,
                    schema='staging')
    # ### end Alembic commands ###
