"""align_consolidated_data_table_with_all_source_fields_fully

Revision ID: 82388c05cf92
Revises: 46c5464fae9b
Create Date: 2025-05-07 06:04:47.854106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82388c05cf92'
down_revision: Union[str, None] = '46c5464fae9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consolidated_data', sa.Column('ann_employee_type_key', sa.String(length=50), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('hf_employee_type_key', sa.String(length=50), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('med_employee_type_key', sa.String(length=50), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('pen_employee_type_key', sa.String(length=50), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_employee_unique_id', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('sal_establishment_type_name', sa.Text(), nullable=True), schema='staging')
    op.add_column('consolidated_data', sa.Column('tax_employee_type_key', sa.String(length=50), nullable=True), schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consolidated_data', 'tax_employee_type_key', schema='staging')
    op.drop_column('consolidated_data', 'sal_establishment_type_name', schema='staging')
    op.drop_column('consolidated_data', 'sal_employee_unique_id', schema='staging')
    op.drop_column('consolidated_data', 'pen_employee_type_key', schema='staging')
    op.drop_column('consolidated_data', 'med_employee_type_key', schema='staging')
    op.drop_column('consolidated_data', 'hf_employee_type_key', schema='staging')
    op.drop_column('consolidated_data', 'ann_employee_type_key', schema='staging')
    # ### end Alembic commands ###
