"""revert_consolidated_data_to_long_column_names

Revision ID: 96ee4a0421a7
Revises: c794fd31d8ac
Create Date: 2025-05-07 04:57:21.029116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ee4a0421a7'
down_revision: Union[str, None] = 'c794fd31d8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consolidated_data', 'ann_contribution_base_salary', new_column_name='ann_annuity_contribution_base_salary', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_contribution_base', new_column_name='ann_annuity_contribution_base', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_employer_rate', new_column_name='ann_annuity_employer_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'ann_employer_contribution', new_column_name='ann_annuity_employer_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_employee_rate', new_column_name='ann_annuity_employee_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'ann_employee_contribution', new_column_name='ann_annuity_employee_contribution', existing_type=sa.Numeric(15, 2), schema='staging')

    op.alter_column('consolidated_data', 'hf_contribution_base_salary', new_column_name='hf_housingfund_contribution_base_salary', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_contribution_base', new_column_name='hf_housingfund_contribution_base', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_employer_rate', new_column_name='hf_housingfund_employer_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'hf_employer_contribution', new_column_name='hf_housingfund_employer_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_employee_rate', new_column_name='hf_housingfund_employee_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'hf_employee_contribution', new_column_name='hf_housingfund_employee_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consolidated_data', 'ann_annuity_contribution_base_salary', new_column_name='ann_contribution_base_salary', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_annuity_contribution_base', new_column_name='ann_contribution_base', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_annuity_employer_rate', new_column_name='ann_employer_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'ann_annuity_employer_contribution', new_column_name='ann_employer_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'ann_annuity_employee_rate', new_column_name='ann_employee_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'ann_annuity_employee_contribution', new_column_name='ann_employee_contribution', existing_type=sa.Numeric(15, 2), schema='staging')

    op.alter_column('consolidated_data', 'hf_housingfund_contribution_base_salary', new_column_name='hf_contribution_base_salary', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_housingfund_contribution_base', new_column_name='hf_contribution_base', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_housingfund_employer_rate', new_column_name='hf_employer_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'hf_housingfund_employer_contribution', new_column_name='hf_employer_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'hf_housingfund_employee_rate', new_column_name='hf_employee_rate', existing_type=sa.Numeric(5, 4), schema='staging')
    op.alter_column('consolidated_data', 'hf_housingfund_employee_contribution', new_column_name='hf_employee_contribution', existing_type=sa.Numeric(15, 2), schema='staging')
    # ### end Alembic commands ###
