"""correct_consolidated_sal_column_names_to_match_converter_v3

Revision ID: a384db55776c
Revises: e0fa28be113b
Create Date: 2025-05-07 05:24:52.865426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a384db55776c'
down_revision: Union[str, None] = 'e0fa28be113b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
