"""consolidate_to_single_employee_type_key_in_consolidated_data_model

Revision ID: b59efb0afd10
Revises: 7768bc752c78
Create Date: 2025-05-07 05:50:04.587962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59efb0afd10'
down_revision: Union[str, None] = '7768bc752c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
