"""Add identity to id column of salary_field_mappings

Revision ID: c0315b176ea0
Revises: 608070bdbe77
Create Date: 2025-05-05 01:08:35.496293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0315b176ea0'
down_revision: Union[str, None] = '608070bdbe77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    print("Adding IDENTITY to id column in core.salary_field_mappings")
    # Using execute for direct ALTER TABLE command to add IDENTITY
    op.execute("ALTER TABLE core.salary_field_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    print("IDENTITY added to id column.")


def downgrade() -> None:
    """Downgrade schema."""
    print("Removing IDENTITY from id column in core.salary_field_mappings")
    # Using execute for direct ALTER TABLE command to drop IDENTITY
    op.execute("ALTER TABLE core.salary_field_mappings ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    print("IDENTITY removed from id column.")
