"""remove_salary_petition_worker_post_allowance_from_raw_staging

Revision ID: ca7eee22499b
Revises: 96ee4a0421a7
Create Date: 2025-05-07 05:36:34.999888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7eee22499b'
down_revision: Union[str, None] = '96ee4a0421a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_salary_data_staging', 'salary_petition_worker_post_allowance', schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_salary_data_staging', sa.Column('salary_petition_worker_post_allowance', sa.Numeric(15, 2), nullable=True), schema='staging')
    # ### end Alembic commands ###
