"""align_consolidated_model_with_four_sal_corrections

Revision ID: cc31aa515d5a
Revises: a384db55776c
Create Date: 2025-05-07 05:27:21.845653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc31aa515d5a'
down_revision: Union[str, None] = 'a384db55776c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consolidated_data', 'sal_civil_servant_normative_allowance', new_column_name='sal_salary_civil_servant_normative_allowance', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_transportation_allowance', new_column_name='sal_salary_transportation_allowance', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_salary_position_or_post_wage', new_column_name='sal_position_or_post_wage', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_salary_rank_or_step_wage', new_column_name='sal_rank_or_step_wage', existing_type=sa.Numeric(15, 2), schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consolidated_data', 'sal_salary_civil_servant_normative_allowance', new_column_name='sal_civil_servant_normative_allowance', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_salary_transportation_allowance', new_column_name='sal_transportation_allowance', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_position_or_post_wage', new_column_name='sal_salary_position_or_post_wage', existing_type=sa.Numeric(15, 2), schema='staging')
    op.alter_column('consolidated_data', 'sal_rank_or_step_wage', new_column_name='sal_salary_rank_or_step_wage', existing_type=sa.Numeric(15, 2), schema='staging')
    # ### end Alembic commands ###
