"""Add unit_id and department_id to salary_records

Revision ID: 1fa9a8a67330
Revises: a351e3a9aab9
Create Date: 2025-04-13 16:16:24.322132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa9a8a67330'
down_revision: Union[str, None] = 'a351e3a9aab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_records', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('salary_records', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_salary_records_department_id'), 'salary_records', ['department_id'], unique=False)
    op.create_index(op.f('ix_salary_records_unit_id'), 'salary_records', ['unit_id'], unique=False)
    op.create_foreign_key('fk_salary_record_department', 'salary_records', 'departments', ['department_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('fk_salary_record_unit', 'salary_records', 'units', ['unit_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_salary_record_unit', 'salary_records', type_='foreignkey')
    op.drop_constraint('fk_salary_record_department', 'salary_records', type_='foreignkey')
    op.drop_index(op.f('ix_salary_records_unit_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_department_id'), table_name='salary_records')
    op.drop_column('salary_records', 'department_id')
    op.drop_column('salary_records', 'unit_id')
    # ### end Alembic commands ###
