"""Sync User and Role models after upgrade

Revision ID: 4f724199ecbf
Revises: 366c3882a4d7
Create Date: 2025-04-22 10:08:13.290443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f724199ecbf'
down_revision: Union[str, None] = '366c3882a4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_units')
    op.drop_table('salary_field_mappings')
    op.drop_index('raw_salary_data_staging_ab_soft_reset__airbyte_extracted_at_idx', table_name='raw_salary_data_staging_ab_soft_reset')
    op.drop_index('raw_salary_data_staging_ab_soft_reset__airbyte_raw_id_idx', table_name='raw_salary_data_staging_ab_soft_reset')
    op.drop_table('raw_salary_data_staging_ab_soft_reset')
    op.drop_table('dim_departments')
    op.drop_table('dim_establishment_types')
    op.drop_table('my_first_dbt_model')
    op.drop_table('view_level1_calculations')
    op.drop_constraint('fk_employees_establishment_type_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'establishment_type_id')
    op.add_column('raw_salary_data_staging', sa.Column('_staging_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_人员身份', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_人员职级', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_岗位类别', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_参照正编岗位工资级别', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_参照正编薪级工资级次', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_工资级别', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_工资档次', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_固定薪酬全年应发数', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_一次性补扣发', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_基础绩效奖补扣发', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_职务技术等级工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_级别岗位级别工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_93年工改保留补贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_独生子女父母奖励金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_岗位职务补贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_公务员规范性津贴补贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_公务交通补贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_基础绩效奖', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_见习试用期工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_信访工作人员岗位津贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_奖励绩效补扣发', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_岗位工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_薪级工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_月基础绩效', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_月奖励绩效', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_基本工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_绩效工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_其他补助', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_补发工资', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_津贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_季度绩效考核薪酬', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_补助', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_信访岗位津贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_补扣发合计', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_生活津贴', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_1季度3季度考核绩效奖', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_补发薪级合计', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人缴养老保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人缴医疗保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人缴职业年金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人缴住房公积金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人缴失业保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_个人所得税', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_其他扣款', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_补扣退社保缴费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_补扣退公积金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_补扣个税', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_单位缴养老保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_单位缴医疗保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_单位缴职业年金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_单位缴住房公积金', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_单位缴失业保险费', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_大病医疗单位缴纳', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('other_备注', sa.Text(), nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('_import_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('raw_salary_data_staging', 'id_card_number',
               existing_type=sa.NUMERIC(precision=38, scale=9),
               type_=sa.String(length=18),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'employee_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'employee_unique_id',
               existing_type=sa.NUMERIC(precision=38, scale=9),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'establishment_type_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'pay_period_identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_salary_data_staging', '_airbyte_source_file',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', '_airbyte_source_sheet',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('raw_salary_data_staging_airbyte_tmp__airbyte_extracted_at_idx', table_name='raw_salary_data_staging')
    op.drop_index('raw_salary_data_staging_airbyte_tmp__airbyte_raw_id_idx', table_name='raw_salary_data_staging')
    op.create_index(op.f('ix_raw_salary_data_staging_employee_unique_id'), 'raw_salary_data_staging', ['employee_unique_id'], unique=False)
    op.create_index(op.f('ix_raw_salary_data_staging_id_card_number'), 'raw_salary_data_staging', ['id_card_number'], unique=False)
    op.create_index(op.f('ix_raw_salary_data_staging_pay_period_identifier'), 'raw_salary_data_staging', ['pay_period_identifier'], unique=False)
    op.drop_column('raw_salary_data_staging', 'deduct_self_housing_fund_contribution')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_critical_illness_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_monthly_basic_performance')
    op.drop_column('raw_salary_data_staging', 'job_attr_personnel_rank')
    op.drop_column('raw_salary_data_staging', 'deduct_self_annuity_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_civil_servant_normative_allowance')
    op.drop_column('raw_salary_data_staging', 'salary_petition_post_allowance')
    op.drop_column('raw_salary_data_staging', 'salary_basic_performance_bonus_deduction')
    op.drop_column('raw_salary_data_staging', 'salary_petition_worker_post_allowance')
    op.drop_column('raw_salary_data_staging', 'job_attr_salary_level')
    op.drop_column('raw_salary_data_staging', 'job_attr_ref_official_post_salary_level')
    op.drop_column('raw_salary_data_staging', 'salary_position_or_technical_salary')
    op.drop_column('raw_salary_data_staging', 'salary_allowance')
    op.drop_column('raw_salary_data_staging', '_airbyte_meta')
    op.drop_column('raw_salary_data_staging', 'deduct_self_medical_contribution')
    op.drop_column('raw_salary_data_staging', 'deduct_individual_income_tax')
    op.drop_column('raw_salary_data_staging', 'salary_one_time_deduction')
    op.drop_column('raw_salary_data_staging', 'salary_post_salary')
    op.drop_column('raw_salary_data_staging', 'salary_reform_1993_reserved_subsidy')
    op.drop_column('raw_salary_data_staging', 'salary_quarterly_performance_bonus')
    op.drop_column('raw_salary_data_staging', 'salary_salary_step_backpay_total')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_housing_fund_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_post_position_allowance')
    op.drop_column('raw_salary_data_staging', 'salary_monthly_reward_performance')
    op.drop_column('raw_salary_data_staging', '_airbyte_extracted_at')
    op.drop_column('raw_salary_data_staging', 'salary_transportation_allowance')
    op.drop_column('raw_salary_data_staging', 'deduct_social_insurance_adjustment')
    op.drop_column('raw_salary_data_staging', 'job_attr_post_category')
    op.drop_column('raw_salary_data_staging', 'other_remarks')
    op.drop_column('raw_salary_data_staging', 'salary_basic_performance_bonus')
    op.drop_column('raw_salary_data_staging', 'salary_rank_or_post_grade_salary')
    op.drop_column('raw_salary_data_staging', '_airbyte_raw_id')
    op.drop_column('raw_salary_data_staging', 'salary_only_child_parents_reward')
    op.drop_column('raw_salary_data_staging', 'job_attr_ref_official_salary_step')
    op.drop_column('raw_salary_data_staging', 'job_attr_salary_grade')
    op.drop_column('raw_salary_data_staging', 'job_attr_personnel_identity')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_pension_contribution')
    op.drop_column('raw_salary_data_staging', 'deduct_tax_adjustment')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_annuity_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_subsidy')
    op.drop_column('raw_salary_data_staging', 'job_attr_annual_fixed_salary_amount')
    op.drop_column('raw_salary_data_staging', 'salary_salary_step')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_unemployment_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_salary_backpay')
    op.drop_column('raw_salary_data_staging', 'salary_reward_performance_deduction')
    op.drop_column('raw_salary_data_staging', 'deduct_other_deductions')
    op.drop_column('raw_salary_data_staging', 'salary_total_backpay_amount')
    op.drop_column('raw_salary_data_staging', 'salary_other_allowance')
    op.drop_column('raw_salary_data_staging', '_airbyte_generation_id')
    op.drop_column('raw_salary_data_staging', 'salary_basic_salary')
    op.drop_column('raw_salary_data_staging', 'deduct_self_unemployment_contribution')
    op.drop_column('raw_salary_data_staging', 'deduct_housing_fund_adjustment')
    op.drop_column('raw_salary_data_staging', 'contrib_employer_medical_contribution')
    op.drop_column('raw_salary_data_staging', 'salary_probation_salary')
    op.drop_column('raw_salary_data_staging', 'salary_performance_salary')
    op.drop_column('raw_salary_data_staging', 'salary_living_allowance')
    op.drop_column('raw_salary_data_staging', 'salary_total_deduction_adjustment')
    op.drop_column('raw_salary_data_staging', 'deduct_self_pension_contribution')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('salary_records', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('salary_records', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('salary_records', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('salary_records', sa.Column('pay_period_start_date', sa.Date(), nullable=False))
    op.add_column('salary_records', sa.Column('pay_period_end_date', sa.Date(), nullable=False))
    op.add_column('salary_records', sa.Column('other_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('salary_records', 'employee_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('salary_records', 'establishment_type_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.create_index(op.f('ix_salary_records_department_id'), 'salary_records', ['department_id'], unique=False)
    op.create_index(op.f('ix_salary_records_employee_id'), 'salary_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_records_establishment_type_id'), 'salary_records', ['establishment_type_id'], unique=False)
    op.create_index(op.f('ix_salary_records_pay_period_end_date'), 'salary_records', ['pay_period_end_date'], unique=False)
    op.create_index(op.f('ix_salary_records_pay_period_start_date'), 'salary_records', ['pay_period_start_date'], unique=False)
    op.create_index(op.f('ix_salary_records_unit_id'), 'salary_records', ['unit_id'], unique=False)
    op.create_foreign_key(None, 'salary_records', 'employees', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'salary_records', 'establishment_types', ['establishment_type_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('fk_salary_record_unit', 'salary_records', 'units', ['unit_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('fk_salary_record_department', 'salary_records', 'departments', ['department_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('salary_records', 'other_remarks')
    op.drop_column('salary_records', 'pay_period_identifier')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('salary_records', sa.Column('pay_period_identifier', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('salary_records', sa.Column('other_remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_salary_record_department', 'salary_records', type_='foreignkey')
    op.drop_constraint('fk_salary_record_unit', 'salary_records', type_='foreignkey')
    op.drop_constraint(None, 'salary_records', type_='foreignkey')
    op.drop_constraint(None, 'salary_records', type_='foreignkey')
    op.drop_index(op.f('ix_salary_records_unit_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_pay_period_start_date'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_pay_period_end_date'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_establishment_type_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_employee_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_department_id'), table_name='salary_records')
    op.alter_column('salary_records', 'establishment_type_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('salary_records', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.drop_column('salary_records', 'other_info')
    op.drop_column('salary_records', 'pay_period_end_date')
    op.drop_column('salary_records', 'pay_period_start_date')
    op.drop_column('salary_records', 'department_id')
    op.drop_column('salary_records', 'unit_id')
    op.drop_column('salary_records', 'id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.add_column('raw_salary_data_staging', sa.Column('deduct_self_pension_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_total_deduction_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_living_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_performance_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_probation_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_medical_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_housing_fund_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_self_unemployment_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_basic_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('_airbyte_generation_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_other_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_total_backpay_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_other_deductions', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_reward_performance_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_salary_backpay', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_unemployment_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_salary_step', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_annual_fixed_salary_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_subsidy', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_annuity_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_tax_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_pension_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_personnel_identity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_salary_grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_ref_official_salary_step', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_only_child_parents_reward', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('_airbyte_raw_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('raw_salary_data_staging', sa.Column('salary_rank_or_post_grade_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_basic_performance_bonus', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('other_remarks', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_post_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_social_insurance_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_transportation_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('_airbyte_extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('raw_salary_data_staging', sa.Column('salary_monthly_reward_performance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_post_position_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_housing_fund_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_salary_step_backpay_total', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_quarterly_performance_bonus', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_reform_1993_reserved_subsidy', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_post_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_one_time_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_individual_income_tax', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_self_medical_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('_airbyte_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('raw_salary_data_staging', sa.Column('salary_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_position_or_technical_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_ref_official_post_salary_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_salary_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_petition_worker_post_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_basic_performance_bonus_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_petition_post_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_civil_servant_normative_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_self_annuity_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('job_attr_personnel_rank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('salary_monthly_basic_performance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('contrib_employer_critical_illness_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.add_column('raw_salary_data_staging', sa.Column('deduct_self_housing_fund_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_raw_salary_data_staging_pay_period_identifier'), table_name='raw_salary_data_staging')
    op.drop_index(op.f('ix_raw_salary_data_staging_id_card_number'), table_name='raw_salary_data_staging')
    op.drop_index(op.f('ix_raw_salary_data_staging_employee_unique_id'), table_name='raw_salary_data_staging')
    op.create_index('raw_salary_data_staging_airbyte_tmp__airbyte_raw_id_idx', 'raw_salary_data_staging', ['_airbyte_raw_id'], unique=False)
    op.create_index('raw_salary_data_staging_airbyte_tmp__airbyte_extracted_at_idx', 'raw_salary_data_staging', ['_airbyte_extracted_at'], unique=False)
    op.alter_column('raw_salary_data_staging', '_airbyte_source_sheet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', '_airbyte_source_file',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'pay_period_identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_salary_data_staging', 'establishment_type_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'employee_unique_id',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=9),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'employee_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('raw_salary_data_staging', 'id_card_number',
               existing_type=sa.String(length=18),
               type_=sa.NUMERIC(precision=38, scale=9),
               existing_nullable=True)
    op.drop_column('raw_salary_data_staging', '_import_timestamp')
    op.drop_column('raw_salary_data_staging', 'other_备注')
    op.drop_column('raw_salary_data_staging', 'contrib_大病医疗单位缴纳')
    op.drop_column('raw_salary_data_staging', 'contrib_单位缴失业保险费')
    op.drop_column('raw_salary_data_staging', 'contrib_单位缴住房公积金')
    op.drop_column('raw_salary_data_staging', 'contrib_单位缴职业年金')
    op.drop_column('raw_salary_data_staging', 'contrib_单位缴医疗保险费')
    op.drop_column('raw_salary_data_staging', 'contrib_单位缴养老保险费')
    op.drop_column('raw_salary_data_staging', 'deduct_补扣个税')
    op.drop_column('raw_salary_data_staging', 'deduct_补扣退公积金')
    op.drop_column('raw_salary_data_staging', 'deduct_补扣退社保缴费')
    op.drop_column('raw_salary_data_staging', 'deduct_其他扣款')
    op.drop_column('raw_salary_data_staging', 'deduct_个人所得税')
    op.drop_column('raw_salary_data_staging', 'deduct_个人缴失业保险费')
    op.drop_column('raw_salary_data_staging', 'deduct_个人缴住房公积金')
    op.drop_column('raw_salary_data_staging', 'deduct_个人缴职业年金')
    op.drop_column('raw_salary_data_staging', 'deduct_个人缴医疗保险费')
    op.drop_column('raw_salary_data_staging', 'deduct_个人缴养老保险费')
    op.drop_column('raw_salary_data_staging', 'salary_补发薪级合计')
    op.drop_column('raw_salary_data_staging', 'salary_1季度3季度考核绩效奖')
    op.drop_column('raw_salary_data_staging', 'salary_生活津贴')
    op.drop_column('raw_salary_data_staging', 'salary_补扣发合计')
    op.drop_column('raw_salary_data_staging', 'salary_信访岗位津贴')
    op.drop_column('raw_salary_data_staging', 'salary_补助')
    op.drop_column('raw_salary_data_staging', 'salary_季度绩效考核薪酬')
    op.drop_column('raw_salary_data_staging', 'salary_津贴')
    op.drop_column('raw_salary_data_staging', 'salary_补发工资')
    op.drop_column('raw_salary_data_staging', 'salary_其他补助')
    op.drop_column('raw_salary_data_staging', 'salary_绩效工资')
    op.drop_column('raw_salary_data_staging', 'salary_基本工资')
    op.drop_column('raw_salary_data_staging', 'salary_月奖励绩效')
    op.drop_column('raw_salary_data_staging', 'salary_月基础绩效')
    op.drop_column('raw_salary_data_staging', 'salary_薪级工资')
    op.drop_column('raw_salary_data_staging', 'salary_岗位工资')
    op.drop_column('raw_salary_data_staging', 'salary_奖励绩效补扣发')
    op.drop_column('raw_salary_data_staging', 'salary_信访工作人员岗位津贴')
    op.drop_column('raw_salary_data_staging', 'salary_见习试用期工资')
    op.drop_column('raw_salary_data_staging', 'salary_基础绩效奖')
    op.drop_column('raw_salary_data_staging', 'salary_公务交通补贴')
    op.drop_column('raw_salary_data_staging', 'salary_公务员规范性津贴补贴')
    op.drop_column('raw_salary_data_staging', 'salary_岗位职务补贴')
    op.drop_column('raw_salary_data_staging', 'salary_独生子女父母奖励金')
    op.drop_column('raw_salary_data_staging', 'salary_93年工改保留补贴')
    op.drop_column('raw_salary_data_staging', 'salary_级别岗位级别工资')
    op.drop_column('raw_salary_data_staging', 'salary_职务技术等级工资')
    op.drop_column('raw_salary_data_staging', 'salary_基础绩效奖补扣发')
    op.drop_column('raw_salary_data_staging', 'salary_一次性补扣发')
    op.drop_column('raw_salary_data_staging', 'job_attr_固定薪酬全年应发数')
    op.drop_column('raw_salary_data_staging', 'job_attr_工资档次')
    op.drop_column('raw_salary_data_staging', 'job_attr_工资级别')
    op.drop_column('raw_salary_data_staging', 'job_attr_参照正编薪级工资级次')
    op.drop_column('raw_salary_data_staging', 'job_attr_参照正编岗位工资级别')
    op.drop_column('raw_salary_data_staging', 'job_attr_岗位类别')
    op.drop_column('raw_salary_data_staging', 'job_attr_人员职级')
    op.drop_column('raw_salary_data_staging', 'job_attr_人员身份')
    op.drop_column('raw_salary_data_staging', '_staging_id')
    op.add_column('employees', sa.Column('establishment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_employees_establishment_type_id', 'employees', 'establishment_types', ['establishment_type_id'], ['id'])
    op.create_table('view_level1_calculations',
    sa.Column('employee_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pay_period_identifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('establishment_type_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('employee_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_card_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('establishment_type_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_personnel_identity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_personnel_rank', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_post_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_ref_official_post_salary_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_ref_official_salary_step', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_salary_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_salary_grade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_attr_annual_fixed_salary_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_one_time_deduction', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_bonus_deduction', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_deduction', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_incentive_performance_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_position_or_technical_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_rank_or_post_grade_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_reform_1993_reserved_subsidy', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_only_child_parents_reward', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_post_position_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_civil_servant_normative_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_transportation_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_bonus', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_probation_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_petition_worker_post_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_reward_performance_deduction', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_post_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_salary_step', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_monthly_basic_performance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_monthly_reward_performance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_basic_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_performance_salary', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_other_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_salary_backpay', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_quarterly_performance_bonus', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_subsidy', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_petition_post_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_total_deduction_adjustment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_living_allowance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_salary_step_backpay_total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_total_backpay_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_self_pension_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_self_medical_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_self_annuity_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_self_housing_fund_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_self_unemployment_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_individual_income_tax', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_other_deductions', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_social_insurance_adjustment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_housing_fund_adjustment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deduct_tax_adjustment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_pension_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_medical_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_annuity_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_housing_fund_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_unemployment_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_critical_illness_contribution', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('other_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('calc_xiaoji', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('calc_personal_deductions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('calc_total_payable', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('calc_net_pay', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('my_first_dbt_model',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('dim_establishment_types',
    sa.Column('establishment_type_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('establishment_type_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('dim_departments',
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('department_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('raw_salary_data_staging_ab_soft_reset',
    sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_remarks', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('id_card_number', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_subsidy', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('employee_unique_id', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_post_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_salary_step', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_basic_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('_airbyte_source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_airbyte_source_sheet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deduct_tax_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_salary_grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_attr_salary_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pay_period_identifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_salary_backpay', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_post_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_other_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_other_deductions', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('establishment_type_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_attr_personnel_rank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_living_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_probation_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_one_time_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_performance_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_personnel_identity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_total_backpay_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_individual_income_tax', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_housing_fund_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_bonus', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_petition_post_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_post_position_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_transportation_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_self_annuity_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_self_medical_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_self_pension_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_monthly_basic_performance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_only_child_parents_reward', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_rank_or_post_grade_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_salary_step_backpay_total', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_ref_official_salary_step', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_monthly_reward_performance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_total_deduction_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_social_insurance_adjustment', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_quarterly_performance_bonus', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_annual_fixed_salary_amount', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_position_or_technical_salary', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_reform_1993_reserved_subsidy', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_reward_performance_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_annuity_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_medical_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_pension_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_self_housing_fund_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('deduct_self_unemployment_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_petition_worker_post_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('job_attr_ref_official_post_salary_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_basic_performance_bonus_deduction', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('salary_civil_servant_normative_allowance', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_housing_fund_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_unemployment_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('contrib_employer_critical_illness_contribution', sa.NUMERIC(precision=38, scale=9), autoincrement=False, nullable=True),
    sa.Column('_airbyte_raw_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('_airbyte_extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_airbyte_generation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('_airbyte_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False)
    )
    op.create_index('raw_salary_data_staging_ab_soft_reset__airbyte_raw_id_idx', 'raw_salary_data_staging_ab_soft_reset', ['_airbyte_raw_id'], unique=False)
    op.create_index('raw_salary_data_staging_ab_soft_reset__airbyte_extracted_at_idx', 'raw_salary_data_staging_ab_soft_reset', ['_airbyte_extracted_at'], unique=False)
    op.create_table('salary_field_mappings',
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_intermediate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_name', name='pk_salary_field_mappings')
    )
    op.create_table('dim_units',
    sa.Column('unit_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
