"""Create raw_salary_data_staging table

Revision ID: deb479f55e83
Revises: 1fa9a8a67330
Create Date: 2025-04-13 21:04:43.866524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deb479f55e83'
down_revision: Union[str, None] = '1fa9a8a67330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_salary_data_staging',
    sa.Column('_staging_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_card_number', sa.String(length=18), nullable=True),
    sa.Column('employee_name', sa.Text(), nullable=True),
    sa.Column('employee_unique_id', sa.Text(), nullable=True),
    sa.Column('establishment_type_name', sa.Text(), nullable=True),
    sa.Column('pay_period_identifier', sa.String(length=7), nullable=False),
    sa.Column('job_attr_人员身份', sa.Text(), nullable=True),
    sa.Column('job_attr_人员职级', sa.Text(), nullable=True),
    sa.Column('job_attr_岗位类别', sa.Text(), nullable=True),
    sa.Column('job_attr_参照正编岗位工资级别', sa.Text(), nullable=True),
    sa.Column('job_attr_参照正编薪级工资级次', sa.Text(), nullable=True),
    sa.Column('job_attr_工资级别', sa.Text(), nullable=True),
    sa.Column('job_attr_工资档次', sa.Text(), nullable=True),
    sa.Column('job_attr_固定薪酬全年应发数', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_一次性补扣发', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_基础绩效奖补扣发', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_职务技术等级工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_级别岗位级别工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_93年工改保留补贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_独生子女父母奖励金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_岗位职务补贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_公务员规范性津贴补贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_公务交通补贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_基础绩效奖', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_见习试用期工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_信访工作人员岗位津贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_奖励绩效补扣发', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_岗位工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_薪级工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_月基础绩效', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_月奖励绩效', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_基本工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_绩效工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_其他补助', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_补发工资', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_津贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_季度绩效考核薪酬', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_补助', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_信访岗位津贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_补扣发合计', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_生活津贴', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_1季度3季度考核绩效奖', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_补发薪级合计', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人缴养老保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人缴医疗保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人缴职业年金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人缴住房公积金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人缴失业保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_个人所得税', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_其他扣款', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_补扣退社保缴费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_补扣退公积金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deduct_补扣个税', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_单位缴养老保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_单位缴医疗保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_单位缴职业年金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_单位缴住房公积金', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_单位缴失业保险费', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contrib_大病医疗单位缴纳', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_备注', sa.Text(), nullable=True),
    sa.Column('_airbyte_source_file', sa.Text(), nullable=True),
    sa.Column('_airbyte_source_sheet', sa.Text(), nullable=True),
    sa.Column('_import_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('_staging_id')
    )
    op.create_index(op.f('ix_raw_salary_data_staging_employee_unique_id'), 'raw_salary_data_staging', ['employee_unique_id'], unique=False)
    op.create_index(op.f('ix_raw_salary_data_staging_id_card_number'), 'raw_salary_data_staging', ['id_card_number'], unique=False)
    op.create_index(op.f('ix_raw_salary_data_staging_pay_period_identifier'), 'raw_salary_data_staging', ['pay_period_identifier'], unique=False)
    
    # Comment out drops as these objects likely don't exist anymore
    # op.drop_index('salary_record_202404__airbyte_extracted_at_idx', table_name='salary_record_202404')
    # op.drop_index('salary_record_202404__airbyte_raw_id_idx', table_name='salary_record_202404')
    # op.drop_table('salary_record_202404')
    # op.drop_table('my_first_dbt_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out corresponding creates in downgrade if needed
    # op.create_table('my_first_dbt_model', ...)
    # op.create_table('salary_record_202404', ...)
    # op.create_index('salary_record_202404__airbyte_raw_id_idx', ...)
    # op.create_index('salary_record_202404__airbyte_extracted_at_idx', ...)

    op.drop_index(op.f('ix_raw_salary_data_staging_pay_period_identifier'), table_name='raw_salary_data_staging')
    op.drop_index(op.f('ix_raw_salary_data_staging_id_card_number'), table_name='raw_salary_data_staging')
    op.drop_index(op.f('ix_raw_salary_data_staging_employee_unique_id'), table_name='raw_salary_data_staging')
    op.drop_table('raw_salary_data_staging')
    # ### end Alembic commands ###
