{{
  config(
    materialized='view'
  )
}}

SELECT
    employee_name AS "姓名",
    id_card_number AS "身份证号",
    calc_total_payable AS "应发工资合计",
    calc_net_pay AS "实发工资",
    deduct_other_deductions AS "其他扣款",
    calc_personal_deductions AS "扣发合计",
    salary_position_or_technical_salary AS "职务技术等级工资",
    salary_only_child_parents_reward AS "独生子女父母奖励金",
    salary_transportation_allowance AS "公务交通补贴",
    salary_incentive_performance_salary AS "奖励性绩效工资",
    salary_basic_performance_bonus AS "基础绩效奖",
    salary_basic_performance_salary AS "基础性绩效工资",
    salary_salary_backpay AS "补发工资",
    salary_post_position_allowance AS "岗位职务补贴",
    salary_post_salary AS "事业单位工作人员岗位工资",
    salary_petition_worker_post_allowance AS "信访工作人员岗位津贴",
    salary_rank_or_post_grade_salary AS "级别岗位级别工资",
    salary_reform_1993_reserved_subsidy AS "九三年工改保留津补贴",
    salary_probation_salary AS "见习试用期工资",
    salary_salary_step AS "薪级工资",
    deduct_self_pension_contribution AS "个人缴养老保险费",
    deduct_self_medical_contribution AS "个人缴医疗保险费",
    deduct_self_annuity_contribution AS "个人缴职业年金",
    deduct_self_housing_fund_contribution AS "个人缴住房公积金",
    deduct_individual_income_tax AS "个人所得税",
    employee_id AS "员工ID",
    pay_period_identifier AS "工资期间",
    establishment_type_id AS "编制ID",
    department_name AS "部门",
    unit_name AS "单位",
    establishment_type_name AS "编制类型",
    job_attr_personnel_identity AS "人员身份",
    job_attr_personnel_rank AS "人员职级",
    job_attr_post_category AS "岗位类别",
    job_attr_ref_official_post_salary_level AS "参照正编岗位工资级别",
    job_attr_ref_official_salary_step AS "参照正编薪级工资级次",
    job_attr_salary_level AS "工资级别",
    job_attr_salary_grade AS "工资档次",
    job_attr_annual_fixed_salary_amount AS "固定薪酬全年应发数",
    salary_one_time_deduction AS "一次性补扣发",
    salary_basic_performance_bonus_deduction AS "基础绩效奖补扣发",
    salary_basic_performance_deduction AS "基础绩效补扣发",
    salary_reward_performance_deduction AS "奖励绩效补扣发",
    salary_monthly_basic_performance AS "月基础绩效",
    salary_monthly_reward_performance AS "月奖励绩效",
    salary_basic_salary AS "基本工资",
    salary_performance_salary AS "绩效工资",
    salary_other_allowance AS "其他补助",
    salary_allowance AS "津贴",
    salary_quarterly_performance_bonus AS "季度绩效考核薪酬",
    salary_subsidy AS "补助",
    salary_petition_post_allowance AS "信访岗位津贴",
    salary_total_deduction_adjustment AS "补扣发合计",
    salary_living_allowance AS "生活津贴",
    salary_salary_step_backpay_total AS "补发薪级合计",
    salary_total_backpay_amount AS "补发合计",
    deduct_self_unemployment_contribution AS "个人缴失业保险费",
    deduct_social_insurance_adjustment AS "补扣退社保缴费",
    deduct_housing_fund_adjustment AS "补扣退公积金",
    deduct_tax_adjustment AS "补扣个税",
    contrib_employer_pension_contribution AS "单位缴养老保险费",
    contrib_employer_medical_contribution AS "单位缴医疗保险费",
    contrib_employer_annuity_contribution AS "单位缴职业年金",
    contrib_employer_housing_fund_contribution AS "单位缴住房公积金",
    contrib_employer_unemployment_contribution AS "单位缴失业保险费",
    contrib_employer_critical_illness_contribution AS "大病医疗单位缴纳",
    other_remarks AS "备注",
    created_at AS "创建时间",
    updated_at AS "更新时间",
    calc_xiaoji AS "小计"
FROM {{ ref('view_level1_calculations') }}
WHERE establishment_type_name = '事业' 