import React, { useEffect, useMemo, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { RouterProvider, type createBrowserRouter } from 'react-router-dom';
import { App } from 'antd';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
// Stagewise toolbar integration (development only)
import { StagewiseToolbar } from '@stagewise/toolbar-react';
import { ReactPlugin } from '@stagewise-plugins/react';
import usePayrollConfigStore from './store/payrollConfigStore';
import useHrLookupStore from './store/hrLookupStore';
import { fetchAllLookupTypesAndCache } from './services/lookupService';

// 导入 Redux hooks 和 selectors
import { useSelector, useDispatch } from 'react-redux';
import {
  selectChatbotIsLoading,
  selectChatbotIsEnabled,
  selectChatbotIsConfigured,
  selectChatbotToken,
  selectChatbotBaseUrl,
  selectChatbotCustomCss,
  selectChatbotCustomJs,
  selectChatbotSystemVariables
} from './store/chatbotConfigSlice';
import { fetchCurrentUserDetails, rehydrateAuth } from './store/authSlice';
import { jwtDecode } from 'jwt-decode';
import type { RootState, AppDispatch } from './store'; // 导入 RootState 和 AppDispatch 类型

type AppRouter = ReturnType<typeof createBrowserRouter>;

interface AppWrapperProps {
  router: AppRouter;
}

const queryClient = new QueryClient();

// Define a placeholder nonce. In a real application, this should be dynamically generated by the server.
// const CSP_NONCE = 'ZWNhZGE5YTEtOGQwMC00ZGQ1LWEzZDQtZWU3YWM2OWQwMzI0'; // Removed hardcoded nonce

const AppWrapper: React.FC<AppWrapperProps> = ({ router }) => {
  const dispatch = useDispatch<AppDispatch>();
  
  // 从 Redux store 获取认证状态
  const authToken = useSelector((state: RootState) => state.auth.authToken);
  const currentUser = useSelector((state: RootState) => state.auth.currentUser);
  const currentUserNumericId = useSelector((state: RootState) => state.auth.currentUserNumericId);
  const isLoadingUser = useSelector((state: RootState) => state.auth.isLoadingUser);
  
  const fetchPayrollConfigs = usePayrollConfigStore(state => state.fetchComponentDefinitions);
  const fetchHrLookups = useHrLookupStore(state => state.fetchLookup);

  // 从 Redux store 中获取 chatbot 配置状态
  const chatbotIsLoading = useSelector(selectChatbotIsLoading);
  const chatbotIsEnabled = useSelector(selectChatbotIsEnabled);
  const chatbotIsConfigured = useSelector(selectChatbotIsConfigured);
  const chatbotConfigToken = useSelector(selectChatbotToken);
  const chatbotConfigBaseUrl = useSelector(selectChatbotBaseUrl);
  const chatbotConfigCustomCss = useSelector(selectChatbotCustomCss);
  const chatbotConfigCustomJs = useSelector(selectChatbotCustomJs);
  const chatbotSystemVariables = useSelector(selectChatbotSystemVariables);

  // 使用用户配置的baseUrl来构建脚本URL，不再使用硬编码的URL
  const DIFY_EMBED_SCRIPT_SRC = chatbotConfigBaseUrl ?
    `${chatbotConfigBaseUrl.replace(/\/$/, '')}/embed.min.js` :
    "";

  const chatbotSystemVariablesJson = useMemo(() => JSON.stringify(chatbotSystemVariables), [chatbotSystemVariables]);

  // 认证初始化逻辑
  const initializeAuth = useCallback(() => {
    // 尝试从 localStorage 恢复认证状态
    try {
      const storedAuthData = localStorage.getItem('auth-storage');
      if (storedAuthData) {
        const parsedAuthData = JSON.parse(storedAuthData);
        
        // 检查 token 是否过期
        if (parsedAuthData.authToken) {
          const decodedToken = jwtDecode<{ exp?: number }>(parsedAuthData.authToken);
          const currentTime = Date.now() / 1000;
          
          if (decodedToken.exp && decodedToken.exp < currentTime) {
            // Token 过期，清除存储
            localStorage.removeItem('auth-storage');
            return;
          }
          
          // Token 有效，恢复状态
          dispatch(rehydrateAuth(parsedAuthData));
          
          // 如果有用户 ID，获取最新用户信息
          if (parsedAuthData.currentUserNumericId) {
            dispatch(fetchCurrentUserDetails(parsedAuthData.currentUserNumericId));
          }
        }
      }
    } catch (error) {
      console.error('Error initializing auth:', error);
      localStorage.removeItem('auth-storage');
    }
  }, [dispatch]);

  useEffect(() => {
    initializeAuth();
  }, [initializeAuth]);

  useEffect(() => {
    if (authToken) {
      fetchPayrollConfigs();
    } else {
    }
  }, [authToken, fetchPayrollConfigs]);

  useEffect(() => {
    if (authToken) {
      
      // 🚀 优化：分批加载，减少并发请求
      const loadLookupsBatch = async () => {
        try {
          // 第一批：最重要的基础数据
          await Promise.all([
            fetchHrLookups('genders'),
            fetchHrLookups('departments'),
            fetchHrLookups('personnelCategories')
          ]);
          
          // 延迟100ms后加载第二批
          setTimeout(async () => {
            await Promise.all([
              fetchHrLookups('maritalStatuses'),
              fetchHrLookups('educationLevels'),
              fetchHrLookups('employmentTypes'),
              fetchHrLookups('employeeStatuses')
            ]);
          }, 100);
          
        } catch (error) {
        }
      };
      
      loadLookupsBatch();
    } else {
    }
  }, [authToken, fetchHrLookups]);

  useEffect(() => {
    if (authToken) {
      fetchAllLookupTypesAndCache();
    } else {
    }
  }, [authToken]);

  useEffect(() => {
    //   '[AppWrapper:useEffect-authWatcher] Auth state changed:',
    //   {
    //     isAuthenticated: !!authToken,
    //     currentUser: currentUser ? currentUser.username : null,
    //     isLoadingUser,
    //   }
    // );
  }, [authToken, currentUser, isLoadingUser]);

  // --- AI Chatbot Integration useEffect Start ---
  useEffect(() => {

    if (chatbotIsLoading) {
      return;
    }

    const scriptIdToUse = chatbotConfigToken || 'dify-chatbot-default-id';

    const cleanupChatbotElements = () => {
      const existingScript = document.getElementById(scriptIdToUse);
      if (existingScript) existingScript.remove();
      const existingConfigScript = document.getElementById('dify-chatbot-config');
      if (existingConfigScript) existingConfigScript.remove();
      const existingCustomStyle = document.getElementById('chatbot-custom-style');
      if (existingCustomStyle) existingCustomStyle.remove();
      const existingCustomLogic = document.getElementById('chatbot-custom-js');
      if (existingCustomLogic) existingCustomLogic.remove();
      const difyWidgetBubble = document.getElementById('dify-chatbot-bubble-button');
      if (difyWidgetBubble) difyWidgetBubble.remove();
      const difyChatbotRoot = document.querySelector('div[id^="dify-chatbotroot-"]');
      if (difyChatbotRoot) difyChatbotRoot.remove();
    };

    if (chatbotIsEnabled && chatbotIsConfigured && chatbotConfigToken && DIFY_EMBED_SCRIPT_SRC && DIFY_EMBED_SCRIPT_SRC.trim() !== '') {
      cleanupChatbotElements();

      const configScript = document.createElement('script');
      configScript.id = 'dify-chatbot-config';
      configScript.nonce = (window as any).__CSP_NONCE__ || ''; // Use global nonce
      const chatbotWindowConfig: { token: string; baseUrl?: string; system_variables: Record<string, any>; dynamicScript?: boolean } = {
        token: chatbotConfigToken!,
        baseUrl: chatbotConfigBaseUrl,
        system_variables: {},
        dynamicScript: true,
      };
      if (chatbotSystemVariables && Array.isArray(chatbotSystemVariables)) {
        chatbotSystemVariables.forEach(sv => {
          if (sv.key && sv.value !== undefined) {
            chatbotWindowConfig.system_variables[sv.key] = sv.value;
          }
        });
      }
      configScript.innerHTML = `window.difyChatbotConfig = ${JSON.stringify(chatbotWindowConfig)};`;
      document.head.appendChild(configScript);

      if (chatbotConfigCustomCss) {
        const styleElement = document.createElement('style');
        styleElement.id = 'chatbot-custom-style';
        styleElement.textContent = chatbotConfigCustomCss;
        styleElement.nonce = (window as any).__CSP_NONCE__ || ''; // Use global nonce
        document.head.appendChild(styleElement);
      }

      if (chatbotConfigCustomJs) {
        const customScriptElement = document.createElement('script');
        customScriptElement.id = 'chatbot-custom-js';
        customScriptElement.textContent = chatbotConfigCustomJs;
        customScriptElement.nonce = (window as any).__CSP_NONCE__ || ''; // Use global nonce
        document.head.appendChild(customScriptElement);
      }

      const embedScript = document.createElement('script');
      embedScript.src = DIFY_EMBED_SCRIPT_SRC;
      embedScript.id = scriptIdToUse;
      embedScript.defer = true;
      embedScript.onload = () => {
      };
      embedScript.onerror = () => {
      };
      document.head.appendChild(embedScript);

    } else {
      cleanupChatbotElements();
    }

    return () => {
      cleanupChatbotElements();
    };
  }, [
    chatbotIsLoading,
    chatbotIsEnabled,
    chatbotIsConfigured,
    chatbotConfigToken,
    chatbotConfigBaseUrl,
    chatbotConfigCustomCss,
    chatbotConfigCustomJs,
    chatbotSystemVariablesJson,
  ]);
  // --- AI Chatbot Integration useEffect End ---

  // Stagewise configuration
  const stagewiseConfig = {
    plugins: [ReactPlugin]
  };

  return (
    // <React.StrictMode> // StrictMode in main.tsx is already commented out
      <QueryClientProvider client={queryClient}>
        <App>
          <RouterProvider router={router} />
          {import.meta.env.DEV && (
            <StagewiseToolbar config={stagewiseConfig} />
          )}
        </App>
      </QueryClientProvider>
    // </React.StrictMode>
  );
};

export default AppWrapper; 